### ISSUE TITLE
feat: more metrics

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/notify-server#48]
```[tasklist]
### Tasks
- [x] Avg & Max (max more important) time to send handle notification request
- [x] Avg & max time to resubscribe to subscriptions
- [x] Clients registering & unregistering
- [x] Current number of subscribed topics
- [x] Successfully processed WS messages
```

**Comment by chris13524** [comment]
These metrics are mostly implemented now. Message metrics are shown, so we can infer things like clients registering/unregistering
